//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _SampleLib.MyDelegate {
    using System;
    using System.ComponentModel;
    using ubta.Reflection;
    using System.Text;
    using System.Linq;
    using System.Reflection;
    using System.Collections.Generic;
    using System.Workflow.ComponentModel;
    using System.Workflow.ComponentModel.Design;
    
    
    [Serializable()]
    [TypeConverter(typeof(ExpandableObjectConverter))]
    [Designer("ubta.UseCase.Designer.UseCaseDesigner")]
    public class Constructor : ubta.UseCase.DefaultActivity {
        
        private System.Collections.Generic.Dictionary<string, System.Type> myTypeRefs;
        
        [NonSerialized()]
        private object _object;
        
        [NonSerialized()]
        private System.IntPtr _method;
        
        [NonSerialized()]
        private string @__rv;
        
        public Constructor() {
            _Init();
        }
        
        public Constructor(System.Runtime.Serialization.SerializationInfo si, System.Runtime.Serialization.StreamingContext sc) {
            _Init();
        }
        
        [Browsable(true)]
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        [Description("Object of type System.Object. Specify a created object reference.")]
        [Category("Parameters")]
        public virtual object @object {
            get {
                return _object;
            }
            set {
                if(_object != value)
{
object ov = _object;
_object = value;
OnParametersChangedInternal("object", ov, value);
};
            }
        }
        
        [Browsable(true)]
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        [Description("Object of type System.IntPtr. Specify a created object reference.")]
        [Category("Parameters")]
        public virtual System.IntPtr method {
            get {
                return _method;
            }
            set {
                if(_method != value)
{
object ov = _method;
_method = value;
OnParametersChangedInternal("method", ov, value);
};
            }
        }
        
        [Browsable(true)]
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        [Description("Object of type System.String. Specify a new or existing object reference.")]
        [Category("ReturnValue")]
        public virtual string _rv {
            get {
                return __rv;
            }
            set {
                __rv = value;
            }
        }
        
        public override string Parameters {
            get {
                StringBuilder sb = new StringBuilder();
sb.Append("(");
sb.Append(null != _object ? ( !_object.ToString().StartsWith("&") && _object.GetType().Equals(typeof(string)) ? "\"" + _object.ToString() + "\"" : _object.ToString()) : "null");
sb.Append(", ");
sb.Append(_method.ToString());
sb.Append(")");
return sb.ToString();
            }
        }
        
        private void _Init() {
            Name = ".ctor";
            myTypeRefs = new Dictionary<string, Type>();
Type[] paramTypes = new Type[] { typeof(System.Object), typeof(System.IntPtr)};			ParameterModifier pm = new ParameterModifier(2);
			ParameterModifier[] paramModifiers = new ParameterModifier[] { pm };
pm[0] = false;
myTypeRefs.Add("object", typeof(System.Object));
pm[1] = false;
myTypeRefs.Add("method", typeof(System.IntPtr));

;
            Action = typeof(SampleLib.MyDelegate).GetConstructor( BindingFlags.Public | BindingFlags.Instance, null, paramTypes, paramModifiers);
            InstanceType = typeof(SampleLib.MyDelegate);;
        }
    }
}
