//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _SampleLib.MySampleClass {
    using System;
    using System.ComponentModel;
    using ubta.Reflection;
    using System.Text;
    using System.Linq;
    using System.Reflection;
    using System.Collections.Generic;
    using System.Workflow.ComponentModel;
    using System.Workflow.ComponentModel.Design;
    
    
    [Serializable()]
    [TypeConverter(typeof(ExpandableObjectConverter))]
    [Designer("ubta.UseCase.Designer.UseCaseDesigner")]
    public class GetSomething_2 : ubta.UseCase.DefaultActivity {
        
        private System.Collections.Generic.Dictionary<string, System.Type> myTypeRefs;
        
        [NonSerialized()]
        private string _param1;
        
        [NonSerialized()]
        private string _GetSomething_2_rv;
        
        public GetSomething_2() {
            _Init();
        }
        
        public GetSomething_2(System.Runtime.Serialization.SerializationInfo si, System.Runtime.Serialization.StreamingContext sc) {
            _Init();
        }
        
        [Browsable(true)]
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        [Description("Object of type SampleLib.IA. Specify a created object reference.")]
        [Category("Parameters")]
        public virtual string param1 {
            get {
                return _param1;
            }
            set {
                if(_param1 != value)
{
object ov = _param1;
_param1 = value;
OnParametersChangedInternal("param1", ov, value);
};
            }
        }
        
        [Browsable(true)]
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        [Description("Object of type System.String. Specify a new or existing object reference.")]
        [Category("ReturnValue")]
        public virtual string GetSomething_2_rv {
            get {
                return _GetSomething_2_rv;
            }
            set {
                _GetSomething_2_rv = value;
            }
        }
        
        public override string Parameters {
            get {
                StringBuilder sb = new StringBuilder();
sb.Append("(");
sb.Append(null != _param1 ? ( !_param1.ToString().StartsWith("&") && _param1.GetType().Equals(typeof(string)) ? "\"" + _param1.ToString() + "\"" : _param1.ToString()) : "null");
sb.Append(")");
return sb.ToString();
            }
        }
        
        private void _Init() {
            Name = "GetSomething";
            myTypeRefs = new Dictionary<string, Type>();
Type[] paramTypes = new Type[] { typeof(System.String)};			ParameterModifier pm = new ParameterModifier(1);
			ParameterModifier[] paramModifiers = new ParameterModifier[] { pm };
pm[0] = false;
myTypeRefs.Add("param1", typeof(SampleLib.IA));

;
            Action = typeof(SampleLib.MySampleClass).GetMethod("GetSomething", BindingFlags.Public | BindingFlags.Instance, null, paramTypes, paramModifiers);
            InstanceType = typeof(SampleLib.MySampleClass);;
        }
    }
}
